[package]
name = "conway-polyhedron-notation-parser"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
polyhedron-ops = { path = "../polyhedron-ops", features = [ "obj" ] }
